### ISSUE TITLE
Postgres deployment not compatible with ARM processors

### ISSUE THREAD

**Issue by kislow** [formancehq/helm#26]
# Expected Behavior

After following the [how-to](https://github.com/formancehq/helm#how-to-use-helm-charts), I would expect the Ledger and Postgres Pods in `STATUS: Running`:

```
NAME                      READY   STATUS    RESTARTS   AGE
ledger-5bff5b8479-bmjkb   1/1     Running   0          7s
postgres-0                1/1     Running   0          36s
```

# Current Behavior

Both pods are in `STATUS: CrashLoopBackOff/Error `

```sh
❯ k get pods
NAME                      READY   STATUS             RESTARTS      AGE
ledger-5bff5b8479-qzrrx   0/1     CrashLoopBackOff   4 (65s ago)   2m44s
postgres-postgresql-0     0/1     CrashLoopBackOff   1 (3s ago)    4s
❯ k logs postgres-postgresql-0
exec /opt/bitnami/scripts/postgresql/entrypoint.sh: exec format error
```

# Failure Information

The [bitnami/postgresql docker image](https://hub.docker.com/r/bitnami/postgresql/tags) only supports AMD.
If postgres pod doesn't run the ledge pods won't run as well because it expects a db.

```
❯ k logs ledger-5bff5b8479-qzrrx 
failed to connect to `host=postgres user=ledger database=ledger`: hostname resolving error (lookup postgres on 10.96.0.10:53: server misbehaving)
```

## Steps to Reproduce

[Follow how-to on github.com/formancehq/helm](https://github.com/formancehq/helm#how-to-use-helm-charts)

**Comment by flemzord** [comment]
Hello @kislow 

Thank you for your feedback 
If you want to deploy the ledger in production, you would need to create a database outside of the Kubernetes cluster / chart helm. 
This Database is very important for the Ledger.

We are preparing the first stable release of our Kubernetes operator, it will be a better solution to deploy the whole stack on Kubernetes 

Regards

**Comment by kislow** [comment]
Hi @flemzord ,

thank you for the quick reply. Initially I was attempting to deploy it locally before running things on production. 
I opened a PR to update the readme for other testers with ARM processors.

"We are preparing the first stable release of our Kubernetes operator, it will be a better solution to deploy the whole stack on Kubernetes" > Looking forward to it.
